import Head from 'next/head';
import Image from 'next/image';

import Header from '../components/Header';
import Sidebar from '../components/SideBar';


import Linechart from '@/components/linechart';
import Transaction from '@/components/Transaction';
// import RecentOrders from '../components/RecentOrders';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='bg-gray-100 min-h-screen'>
        <Sidebar />
        <Header />


        <div className="flex flex-col p-4 gap-4 ml-28">
          <Linechart />
          <Transaction />
          {/* <RecentOrders /> */}
        </div>
      </main>
    </>
  );
}
